services:
  gate-nambaone:
    build: .
    command: web
    environment:
      WEB_SERVICE_PORT: 8000
      LOG_LEVEL: info
      NOTIFICATIONS_PREFIX: /nambaone
      ELASTIC_APM_ENABLED: "false"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/v2/ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
